version: "3"

networks:
  tddo:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - tddo
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9300"
    ports:
      - "5601:5601"
    networks:
      - tddo
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
    ports:
      - "5001:5001"
    depends_on:
      - elasticsearch
    networks:
      - tddo
  config-server:
    image: tddo-config-server:0.0.1
    container_name: config-server
    ports:
      - "8071:8071"
    networks:
      - tddo
    depends_on:
      - logstash
  discovery-server:
    image: tddo-discovery-server:0.0.1
    container_name: discovery-server
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8072:8072"
    networks:
      - tddo
    depends_on:
      - logstash
      - config-server
  gateway-server:
    image: tddo-gateway-server:0.0.1
    container_name: gateway-server
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8070:8070"
    networks:
      - tddo
    depends_on:
      - discovery-server
      - logstash
      - config-server
  authentication-service:
    image: tddo-authentication-service:0.0.1
    container_name: authentication-service
    ports:
      - "8073:8073"
    networks:
      - tddo
    depends_on:
      - gateway-server

